### ISSUE TITLE
We are still not having rights to Push on remote.

### ISSUE THREAD

**Issue by UgraNarasimha** [gcodersclub/our-first-repo#1]

**Comment by danielacraciun** [comment]
You need to be a part of the organization the repository is in. I have invited you and your invitation is still pending (along with 4 others). If any of you still have this problem and are unsure whether you shared your details with me or not, please message me with your Github username on Slack and I will add you ASAP. Thanks!

**Comment by UgraNarasimha** [comment]
Thankyou, I completed the procedure.It is working!
